### ISSUE TITLE
[Easy first task] Bug: Email button overlaying text 

### ISSUE THREAD

**Issue by matthamil** [egdelwonk/nashdev-jobs#26]
This is an easy-first-task for someone looking to get into OSS or contribute to this project :)

Example: https://jobs.nashdev.com/jobs/4

![image](https://user-images.githubusercontent.com/11802078/29082904-a8444816-7c2c-11e7-85cb-3922411df32f.png)

## Current behavior

The `<div><a href="mailto:` element is overlaying the text above it. 

## Expected behavior

The button should not overlay the text.

**Comment by egdelwonk** [comment]
Thanks for reporting @matthamil!
