### ISSUE TITLE
[Good first task] Bug: String interpolation isn't quite interpolating :)

### ISSUE THREAD

**Issue by matthamil** [egdelwonk/nashdev-jobs#28]
See https://github.com/egdelwonk/nashdev-jobs/blob/master/client/components/Companies/View.js#L86

## Current Behavior

Content that is rendered:
![image](https://user-images.githubusercontent.com/11802078/29139596-17ad4546-7d0d-11e7-8f71-f6e845a375f0.png)

## Expected Behavior

Should call when clicked

**Comment by iamtylerd** [comment]
PR submitted here.
[https://github.com/egdelwonk/nashdev-jobs/pull/30](url)
