### ISSUE TITLE
Job titles and text not resizing to match windows / text being cut off

### ISSUE THREAD

**Issue by joesonghamnida** [egdelwonk/nashdev-jobs#29]
<img width="407" alt="iphone6inspection" src="https://user-images.githubusercontent.com/9257255/29140836-8704de96-7d11-11e7-8996-b16bdc14ff02.png">
Altering Chome's window size (making it more narrow), as well as viewing the site on a smartphone, caused text to be cut off. This was also present in Firefox.
<img width="504" alt="chromewindowresizing" src="https://user-images.githubusercontent.com/9257255/29140835-836a1062-7d11-11e7-8693-fa6902f0d20b.png">
.

**Comment by egdelwonk** [comment]
Thanks for reporting Joe. We'll take a peak.
