### ISSUE TITLE
Bug: Strip @ from slack handles before save

### ISSUE THREAD

**Issue by egdelwonk** [egdelwonk/nashdev-jobs#33]
To keep slack handles consistent when storing and displaying, we should remove the @ prefix. Some users type it, some don't. Probably best to sanitize it and append it when we display on the site.

**Comment by matthewtrask** [comment]
@egdelwonk what page is this saved on? mentoring a jr dev and looking to solve this.

**Comment by egdelwonk** [comment]
It's on the jobs add and edit pages. 

https://github.com/egdelwonk/nashdev-jobs/blob/master/client/components/Jobs/Add.js
https://github.com/egdelwonk/nashdev-jobs/blob/master/client/components/Jobs/Edit.js

Probably would want to strip it on the server before save? ¯\_(ツ)_/¯

**Comment by matthewtrask** [comment]
word, I think its right to strip before save.

**Comment by egdelwonk** [comment]
@matthewtrask Any progress on this? :D

**Comment by matthewtrask** [comment]
I passed it on to the mentee, but Ill double back and get more information. If not, I can get it done :)

**Comment by egdelwonk** [comment]
No big rush! Thanks :D

**Comment by egdelwonk** [comment]
No worries! :D
