### ISSUE TITLE
Enhancement: SlackBot should post the Date in DD/MM/YYY format when a job was added

### ISSUE THREAD

**Issue by matthamil** [egdelwonk/nashdev-jobs#35]
The Slackbot currently posts the following to the Jobs channel in NashDev Slack:

```
*New Job Added* / @@person (First Last)
      
*Software Engineer* at *Company Name* in _Company Location_
Added: Today at 3:19 PM
 ________________________________________________________________________________
```

I want to propose changing the "Added:" line. When a user posts a job, the "Added" line will always read "Added: Today" when the SlackBot posts in the channel when new jobs are added.

The line should read: "Added: 08/21/2017 at 3:19 PM" or a similar DD/MM/YYYY format. When a user is scrolling through the NashDev Jobs channel, it's unclear what day a job was posted by the SlackBot's post alone. The same goes for when a job posting is updated: the "updated" line will also always read "Today".

Example after proposed changes:

```
*New Job Added* / @@person (First Last)
      
*Software Engineer* at *Company Name* in _Company Location_
Added: 08/21/2017 at 3:19 PM
 ________________________________________________________________________________
```

**Comment by daynewright** [comment]
Updated this one.  Still figuring out how to handle two github accounts on my machine ¯\_(ツ)_/¯.
